[package]
name = "lapis-platform"
version.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true

[dependencies]
lapis-app-services = { path = "../app-services" }
lapis-document = { path = "../document" }
lapis-editor-core = { path = "../editor-core" }
lapis-git = { path = "../git" }
lapis-lsp = { path = "../lsp" }
lapis-terminal = { path = "../terminal" }
portable-pty.workspace = true
lapis-task-runner = { path = "../task-runner" }
lapis-workspace = { path = "../workspace" }
rfd.workspace = true
serde.workspace = true
serde_json.workspace = true
tempfile.workspace = true

[dev-dependencies]
