[package]
name = "lapis-desktop-ui"
version.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true

[dependencies]
gpui.workspace = true
lapis-app-services = { path = "../app-services" }
lapis-editor-core = { path = "../editor-core" }
lapis-git = { path = "../git" }
lapis-language = { path = "../language" }
lapis-lsp = { path = "../lsp" }
lapis-task-runner = { path = "../task-runner" }
lapis-terminal = { path = "../terminal" }
lapis-workspace = { path = "../workspace" }
serde_json.workspace = true
