[package]
name = "lapis-backend-state"
version.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true

[dependencies]
lapis-client-api = { path = "../client-api" }
lapis-document = { path = "../document" }
lapis-text = { path = "../text" }

[dev-dependencies]
tempfile.workspace = true
