[package]
name = "lapis"
version.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true

[dependencies]
lapis-app-services = { path = "../../../backend/core/app-services" }
lapis-backend-state = { path = "../../../backend/core/backend-state" }
lapis-client-api = { path = "../../../backend/core/client-api" }
lapis-desktop-ui = { path = "../ui" }
lapis-platform = { path = "../../../backend/local" }
lapis-persistence = { path = "../../../backend/persistence" }
lapis-remote = { path = "../../../backend/remote" }
lapis-settings = { path = "../../../backend/core/settings" }
lapis-task-runner = { path = "../../../features/task-runner" }
