[package]
name = "lapis-remote"
version.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true

[dependencies]
lapis-client-api = { path = "../core/client-api" }
getrandom.workspace = true
sha2.workspace = true
subtle.workspace = true
zeroize.workspace = true

[dev-dependencies]
tempfile.workspace = true
