[package]
name = "lapis-persistence"
version.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true

[dependencies]
lapis-app-services = { path = "../app-services" }
lapis-editor-core = { path = "../editor-core" }
lapis-workspace = { path = "../workspace" }
serde.workspace = true
serde_json.workspace = true
tempfile.workspace = true

[dev-dependencies]
lapis-terminal = { path = "../terminal" }
